name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Create libraries
      run: mkdir libraries

    - name: Download GLM
      run: |
        curl -L -o glm-0.9.9.8.zip https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
        tar -xf glm-0.9.9.8.zip
        move glm libraries

    - name: Download GLEW
      run: |
        curl -L -o glew.zip https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0-win32.zip
        tar -xf glew.zip
        move glew-2.2.0 libraries

    - name: Download SDL2
      run: |
        curl -L -o SDL2.zip https://github.com/libsdl-org/SDL/releases/download/release-2.26.4/SDL2-devel-2.26.4-VC.zip
        tar -xf SDL2.zip
        move SDL2-2.26.4 libraries

    - name: Download & Build cpr
      run: |
        curl -L -o cpr.zip https://github.com/libcpr/cpr/archive/refs/tags/1.10.5.zip
        tar -xf cpr.zip
        move cpr-1.10.5 libraries
        cd libraries/cpr-1.10.5
        cmake -B build/ -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}
        cmake --build build/ --parallel --config ${{env.BUILD_CONFIGURATION}}

    - name: Build TerrainRenderer
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: terrain-renderer
        path: |
          ${{github.workspace}}/x64/${{env.BUILD_CONFIGURATION}}/*.exe
          ${{github.workspace}}/x64/${{env.BUILD_CONFIGURATION}}/*.dll

